### ISSUE TITLE
"Get" or "Read" function?

### ISSUE THREAD

**Issue by jnovack** [fjw/node-simplespi#1]
Does the PWM support a `get` / `read` function so I can get the current value of a channel?

I cannot write c, but I see that you read the values after setting them.  Can you break out the `read` function separately so that I may directly query a channel's value?

**Comment by jnovack** [comment]
The end goal, would then be to write a `pget` and `getRGB` function for node-leddriver, so that we do not need to store a channel's current value in the application layer.

**Comment by mrmowgli** [comment]
After looking  at the C source, it is clear that there is no read function.  Although after looking at it it seems like it is fairly simple to do.

**Comment by jnovack** [comment]
No longer applicable.
